### ISSUE TITLE
cancel a HttpClient request

### ISSUE THREAD

**Issue by david127cu** [ITHit/UserFileSystemSamples#5]
How can I cancel a HttpClient request or change TimeOut after send request?

**Comment by david127cu** [comment]
Add support for CancellationToken in GetFolderAsync, CreateFileAsync

**Comment by dimnorin** [comment]
Unfortunately currently you can only set the timeout before sending a request:  

you can not change timeout after that.

We are working to add a cancelation tokens in future updates.

**Comment by david127cu** [comment]
Thanks
